### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by DevNico** [brumm/tako#10]
I am trying to help fix some of the already open issues e.g. #8 but I'm running into trouble getting the extension running. What I did:
- Cloned the repo
- `yarn install && yarn run build`
- Added the unpacked-extension folder in Chrome

I haven't changed any files yet and get this error: `Error handling response: TypeError: Object(...) is not a function` I honestly can't make much of it, hoping you might now what's happening here.

**Comment by brumm** [comment]
I'm super glad you're wanting to chip in! Not sure what the dev problem is, I'm taking a look now.

In the meantime, can you make sure you're on node v12.14.1 and try again?

**Comment by DevNico** [comment]
Turns out I was still on Node v10.something. I just reinstalled node entirely including yarn and now I'm on:
- Node: v13.12.0
- npm: v6.14.4
- yarn: v1.22.4

In the extension page I found this error: `WebSocket connection to 'ws://localhost:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Edit: Also tried it with the version of node you mentioned but with the same result.

**Comment by brumm** [comment]
This seems to be connected to the extension reloading plugin: https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/86

Can you remove the ExtensionReloader entry in the `webpack.config.js` plugins array and try again? Sorry about the issues!

**Comment by DevNico** [comment]
I finally got it working. The problem it seems was the use of `createRoot` which is still an experimental feature. I replaced it with:
```
ReactDOM.render(
  <GlobalErrorBoundary>
    <Root />
  </GlobalErrorBoundary>,
  mount
)
```

And now it works.

**Comment by brumm** [comment]
Bizarre! Especially because I'm importing `^0.0.0-experimental-aae83a4b9` of react and react-dom respectively, which should be all there is to it. Anyway, I'm glad that things are working for you now!

**Comment by DevNico** [comment]
That just gave me an idea. Removing the `^` makes it work with createRoot again. I searched and tried for the last 3 hours and those little circumflexes were the culprit...

**Comment by brumm** [comment]
Oooh yeah, that's a funky gotcha if you're using weird one-off experimental tags. NPM uses the circumflex by default, but using it here accidentally installs really old versions of react. Still confused why this didn't happen for me 🤷‍♂
