### ISSUE TITLE
Prompt For New Token

### ISSUE THREAD

**Issue by matthewoestreich** [brumm/tako#14]
If I manually remove the access token from my GitHub account, Tako does not prompt for a new token, instead it just throws an error (never letting me update the token)..

I am close to having this ported over to Firefox - this issue is something I noticed during my testing, which I verified is an issue with the existing Chrome extension as well.

I should have a PR tomorrow sometime that fixes this issue + provides Firefox support.

**Comment by brumm** [comment]
Yeah, we're currently not checking anything around this :) Should be a matter of checking for 401s after we did make a request and then remove the token to reset the App.
