### ISSUE TITLE
Future improvements

### ISSUE THREAD

**Issue by DevNico** [brumm/tako#17]
I really like the idea of this project but I do have some things I'd like to propose:
- Add a license e.g. the [GNU GPL 3.0](https://choosealicense.com/licenses/gpl-3.0/)
- Convert the current project to typescript and restructure the files for better maintainability
- Automate build and release process with Github Actions to further improve collaborative development

**Comment by brumm** [comment]
- license will probably be MIT
- hard no on typescript, yes to restructuring
- great idea, i had no idea you could release chrome extensions programmatically
