### ISSUE TITLE
Browser tab becomes unresponsive on attempt to unfold a directory containing '#' in its name

### ISSUE THREAD

**Issue by OleksiyRudenko** [brumm/tako#18]
Browser tab becomes unresponsive on attempt to unfold a directory containing '#' in its name.
Network is all green, Console is clean though.

STR:
1. Navigate to https://github.com/Cyan101/code-examples
2. When filelist gets rendered unfold `daily-programmer` then try to unfold `#312` or `#317`.

Below is the state the browser tab gets stuck at.

![image](https://user-images.githubusercontent.com/8686631/78469776-c8d6ad00-772c-11ea-83ff-2ceaacfc06f5.png)

**Comment by brumm** [comment]
Thanks for reporting this, I'll take a look asap

[Philipp Brumm - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=gajrb)	[gajrb]

**Comment by brumm** [comment]
thanks man! closed in 97b11b0660ceb08443edc87e0b39b78c72931445
