### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by nazimjamil** [brumm/tako#19]
Great extension team, I'd like to use it on an enterprise instance of GitHub, it has a unique URL that doesn't end in *.github.com.

As an engineer,
I would like Tako to work on a custom GitHub domain,
So that I can use it with an enterprise instance of GitHub.

**Comment by madhavarshney** [comment]
If anyone would like to take a stab at this, it seems that there are [a few places where github.com is hardcoded](https://github.com/brumm/tako/search?q=github.com&unscoped_q=github.com) in the codebase. This would need to be made configurable.

If your domain name is not *.github.com, a good starting point would be changing the url in package.json:
https://github.com/brumm/tako/blob/21085207a5c9c69bd25cbc626ad25cca486d4da8/package.json#L30-L34

**Comment by nazimjamil** [comment]
I'll take a look

**Comment by brumm** [comment]
Since I don't have access to Github Enterprise, I am closing this ticket.
