### ISSUE TITLE
Feature request: Firefox extension

### ISSUE THREAD

**Issue by seshaljain** [brumm/tako#2]
Came across your post on Reddit.

Great work! :+1: 

Any chance of a Firefox extension port?

**Comment by djanda97** [comment]
I don’t have experience creating extensions, but I’d be willing to try and help port Tako to Firefox.

**Comment by brumm** [comment]
Go for it! I'm not super experienced either, but from my understanding I'm compatible with the Web Extension standard and I'm not using anything chrome specific. Might be as easy as changing some keys in the manifest file!

**Comment by djanda97** [comment]
@brumm Cool! I'll create a fork and start checking out the code. How did you go about testing the extension in Chrome?

**Comment by brumm** [comment]
FYI, you should talk to @oze4 they're already working on a FF version

**Comment by matthewoestreich** [comment]
See this PR: https://github.com/brumm/tako/pull/16

**Comment by brumm** [comment]
Submission to the add-on store is underway, it'll be available here if it passes review: https://addons.mozilla.org/en-US/firefox/addon/tako-github-file-tree/
