### ISSUE TITLE
Github File edit button is not visible anymore 

### ISSUE THREAD

**Issue by GorvGoyl** [brumm/tako#24]
Go to any repo and open README.md file on github.com, earlier there was an option to directly edit that file inside github.com. With this extension installed that file edit icon is not visible anymore.

**Comment by brumm** [comment]
Yeah, I know. For now you can middle-click on a file- or folder name to open the native page in a new tab.
There's a first draft PR at #13  to provide a file-toolbar, but I'm not happy with the UI yet. I'd probably attempt to render that toolbar in place of the table header. If you're interested in doing this, hop aboard!

**Comment by brumm** [comment]
There's now a dedicated button for this after selecting a file in the preview
![image](https://user-images.githubusercontent.com/170500/93717889-e7185400-fb78-11ea-82e3-c698a5c41f30.png)
