### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by lishine** [brumm/tako#25]
Tako is great!
This extension
https://chrome.google.com/webstore/detail/github-vscode-icons/hoccpcefjcgnabbmojbfoflggkecmpgd/related
doesn't work when using Tako
Is there anything can be done?

**Comment by brumm** [comment]
Hey! Compatibility is unlikely, however I'm be open for someone taking ownership of the feature and building + supporting it!

**Comment by maicol07** [comment]
This can also be extended to: https://github.com/xxhomey19/github-file-icon

**Comment by brumm** [comment]
Hey, since Tako is taking over the complete file view rendering, and also changing folder icons on the fly, it is highly unlikely Tako will be compatible any kind of custom icon extension.
