### ISSUE TITLE
GitHub Design & Repository Refresh

### ISSUE THREAD

**Issue by madhavarshney** [brumm/tako#31]
Github has a new [Design and Repository Refresh](https://www.reddit.com/r/github/comments/hbxu8d/what_do_you_guys_think_of_the_new_github_design/) in feature preview. To support it, making the following change works:

https://github.com/brumm/tako/blob/e981f7845960def9fd6ead2870518742be32bd65/src/constants.js#L1

```diff
-  export const MOUNT_SELECTOR = 'table.files'
+  export const MOUNT_SELECTOR = '.Details [role="grid"]'
```

It seems like GitHub has done away with the `table` and now uses plain `divs`. Unfortunately, there isn't a clear selector that we can use to target the files list, and I'm not sure how reliable the solution above is. Possibly, `aria-labelledby="files"` can also be used or a selector with `.parentElement`, but this needs to be investigated.

Also, the design refresh has updated the icons, so those will have to be updated as well.

| Refresh | Refresh + Tako |
| --- | --- |
| <img alt="Screenshot of GitHub design and repository refresh." src="https://user-images.githubusercontent.com/40002855/85220225-a6812280-b35e-11ea-9bab-76f7d7c25b5c.png"> | <img alt="Screen Shot of GitHub design and repository refresh with Tako" src="https://user-images.githubusercontent.com/40002855/85220271-f4962600-b35e-11ea-842f-38f0860bd8d7.png"> |

**Comment by brumm** [comment]
Hey thank you! I'm glad you tried this and confirmed that this mostly works :) I haven't gotten around to investigating the new mode yet.

~I'm not sure how I want to handle this stuff—ignore it while it's in beta, and implement it once it's used as a default? Or find a way to reliably check whether the design refresh mode is active and make it possible to use it during beta?~

Actually, this was pretty easy to do for both! Now to find a way to tell whether the design update is active

**Comment by tkstang** [comment]
It seems to be completely active now, I never chose to preview it and I cannot switch it back.

**Comment by madhavarshney** [comment]
@brumm @tkstang Just checked and it does seem like that it is the default now.

**Comment by brumm** [comment]
Oh neat, I'll check and push out the release soon. Thanks for checking!

[Philipp Brumm - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=kdo99)	[kdo99]

**Comment by tkstang** [comment]
Any update on this?

**Comment by brumm** [comment]
Sorry, was pretty swamped the past weeks. I have a rough version done which I've been using to test for problems. It should work alright, I'll push it out :)

**Comment by MihaiWill** [comment]
For me doesn't work :(

**Comment by brumm** [comment]
Finally found some time to look at this, and just submitted new versions to both the Firefox and Chrome extensions stores. Should update in 24hrs-ish. Let me know if anything breaks!
