### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by hugo-vrijswijk** [brumm/tako#39]
I realize this is super early and expected, but wanted to create an issue to track it.

GitHub is working on dark mode. I think you can enable it if you opt into beta features, but I got a toggle on the GitHub homepage. You can also enable it by adding the `data-color-mode="dark"` attribute to the root `html` element. This extension does not work properly with dark mode enabled:

![image](https://user-images.githubusercontent.com/10114577/101522596-bda4e280-3987-11eb-92cc-fcbba3837e3d.png)

Without the extension:

![image](https://user-images.githubusercontent.com/10114577/101522653-d01f1c00-3987-11eb-8096-1088036a6f31.png)

Some differences at first glance:

- Folder icon
- Line separator
- Hover color
- Code preview (when clicking on a file)

It looks like GitHub is using css variables for the colours:

![image](https://user-images.githubusercontent.com/10114577/101522997-4885dd00-3988-11eb-9764-3a405cfc927c.png)

**Comment by brumm** [comment]
Thanks for the sleuthing! The CSS vars will help immensely in updating this.

**Comment by hugo-vrijswijk** [comment]
I'm already hacking away a bit at this. I can open a PR with _most_ things working in dark mode, but probably not all

**Comment by brumm** [comment]
Aw! I'm already done :) Sorry I missed this

**Comment by brumm** [comment]
updated extensions are getting pushed to the web stores in a bit

**Comment by brumm** [comment]
let me know what you think!

**Comment by hugo-vrijswijk** [comment]
It looks great! Thanks for the quick action 💪! Looking at the code it was really similar to some of my local changes, but I missed a couple things
