### ISSUE TITLE
Images in MD preview won't render

### ISSUE THREAD

**Issue by OleksiyRudenko** [brumm/tako#4]
Looks like a bug. Not critical though. And it might be reasonable to replace images with some fixed size placeholders (for the preview pane is of fixed dimensions) provided there is a way to open the file in the native mode.

![image](https://user-images.githubusercontent.com/8686631/78217471-dab61700-74c4-11ea-9d20-1153fb3a9af8.png)

**Comment by brumm** [comment]
Yeah, I've noticed that before. It's kind of weird too, because I'm using Github's own markdown rendering service—I'm not actually parsing and rendering the markdown myself, although that would give me more flexibility in how to handle this 🤔

**Comment by DevNico** [comment]
This happens because the image links in the markdown files are getting resolved wrong. e.g. the request for the image `media/logo.png` resolves to `https://github.com/brumm/media/logo.png` which is obviously not the correct url.

**Comment by brumm** [comment]
Which is super weird, because their own markdown renderer resolves it correctly to https://raw.githubusercontent.com/brumm/tako/master/media/logo.png.

That's a bummer, I really did not want to have to render their fancy github-flavored-markdown myself. Oh well!

**Comment by DevNico** [comment]
I would be happy to take a look at this.

**Comment by brumm** [comment]
Go for it!
