### ISSUE TITLE
Update token validation logic for GitHub's new auth token format

### ISSUE THREAD

**Issue by madhavarshney** [brumm/tako#44]
See: https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

The regexes in the following locations have to be updated:

https://github.com/brumm/tako/blob/c6c5dfac42e28620b349c73b2014e62df54b41aa/src/components/AskForToken.js#L7
https://github.com/brumm/tako/blob/c6c5dfac42e28620b349c73b2014e62df54b41aa/src/components/AskForToken.js#L45

The updated regex can range from `\w{40}` to `gh[a-z]_[\da-zA-Z]{36}` or `ghp_[\da-zA-Z]{36}` depending on how strong you want the validation to be.

**Comment by brumm** [comment]
thanks so much for the heads-up! i'll integrate this as soon as i can

**Comment by gaelthas** [comment]
Still not work?
