### ISSUE TITLE
Default file structure view on private repos gets replaced with "Something went boom"

### ISSUE THREAD

**Issue by OleksiyRudenko** [brumm/tako#5]
Kudos to the plugin author. It's a great, really convenient alternative for browsing repo content.

I believe the below might be linked to #1 .

When in private repository the progress spinner runs for a while and finally resolves to an error.
![image](https://user-images.githubusercontent.com/8686631/78215776-033c1200-74c1-11ea-9519-12d426de463d.png)

It is most likely to happen due to incompatibility of a token with current repo (for it is private).

**Update 2020-04-02 10:55 UTC:** there are no issues with private repos of mine. This affects repos in one of the organizations I am a member to. There are no public repos in that particular organization, so cannot tell how it behaves there. In yet another organization I am a member to public repos are treated as expected (no private repos there though).

Possible solution might be to fallback to the default (native) view of file list + optionally offer to add a token. The latter might also require multiple tokens support.

Besides one may not want to grant plugin a permission to read a repo due to organization info security policy requirements, so it might be even better to expose default view while plugin is busy with reading the repo. Still it is important to know it is working.

Please consider the following approach.

1. When there is no token in place (or no any tokens when multiple tokens supported), inject a prompt to add a token (no change in current implementation)
2. When there are any tokens:
(a) expose default view + inject progress bar while plugin reads a repo (possibly trying a matching token)
(b) on success remove the progress bar and replace the view, otherwise replace the progress bar with a warning (smth like "Failed to read a repo due to token expiration or access restrictions") and a prompt to add a token

**Comment by brumm** [comment]
Thanks for reporting this! Private repos are already supported and should work with the current setup, as well as the generated tokens. Could you check the Network tab for failing requests originating from Tako?

**Comment by OleksiyRudenko** [comment]
Here they are.

Console
![image](https://user-images.githubusercontent.com/8686631/78240181-51640c00-74e7-11ea-9156-acdbd5d0ca25.png)

Network
![image](https://user-images.githubusercontent.com/8686631/78240344-8c663f80-74e7-11ea-973e-5447885c5a1c.png)

URL under every `?ref=dev` request name is `https://api.github.com/repos/ORGANIZATION_NAME/REPO_NAME/contents/?ref=dev`

Please note that in this particular case I would prefer a fallback to default file list view rather than adding an access token.

**Comment by OleksiyRudenko** [comment]
With v.0.0.5 comes a better UX. The error reporting is not secretive anymore
![image](https://user-images.githubusercontent.com/8686631/78301193-68cfe300-7541-11ea-9fcf-2c73e286170b.png)
and followed by default/native file view.

It takes time before it resolves. But this is to be resolved rather by a different feature request.

@brumm I'd consider this issue closed. Thank you for the fix
