### ISSUE TITLE
Can't save new token format

### ISSUE THREAD

**Issue by grrowl** [brumm/tako#51]
Related to #45. I tried to work around it by:

1. Inspect element and removing the `disabled` attribute from the Save button
2. The input has attribute `pattern="[\da-f]{40}"` which doesn't match the new token format — should be `pattern="[\da-zA-Z_]{40}"`

"Save" still doesn't work tho :\\\

**Comment by grrowl** [comment]
had a dig in the code and couldn't figure it out, or figure out how to forcefully set new token to storage. love the extension though!

**Comment by brumm** [comment]
Hey folks! Sorry about the token saving issue. I'll get this fixed today :)

**Comment by brumm** [comment]
Okay, this should be fixed in 37232f0f1cf15f445872d9b1b73ada4cf79923d2

Will take a bit to propagate through the extension stores as usual

**Comment by grrowl** [comment]
Danke! Looking forward to re-enabling this awesome extension, it's a bit of a life saver

**Comment by brumm** [comment]
Bitte! I'm glad it's useful to you :)

**Comment by grrowl** [comment]
Is it usual for the Chrome Web Store to take this long to update? It's still on 0.2.4: https://chrome.google.com/webstore/detail/tako-%E2%80%94-github-file-tree/fdmdpnmffpjdkjaapcbdnkhnidhgoabe

**Comment by brumm** [comment]
Hmm. The update might be stuck due to some changed policies or something. Which they don't tell you about haha! I'll check it out in a bit.

**Comment by brumm** [comment]
Hey, 0.2.4 is the latest version, with all token validation removed. Is it still not working for you?
