### ISSUE TITLE
0.2.5 still can't save new token format

### ISSUE THREAD

**Issue by grrowl** [brumm/tako#55]
`pattern="[\da-f]{40}"` is still present in 0.2.5

related #51

**Comment by Maybach91** [comment]
Its not possible to save it at all, so the whole tool got unusable. 👏🏼 @brumm

**Comment by brumm** [comment]
@grrowl Oh, I missed that it's also used in `ReEnterOnInvalidToken`. Are you actually seeing the invalid token view? You can remove and re-add the extension to clear any existing token, that should at least enable you to get in via the regular `AskForToken` flow.

@Maybach91 I do not appreciate the sarcastic clapping.

**Comment by grrowl** [comment]
It's the regular ask for token view as I believe. It's just asking for an access token and a save button but it won't accept the new format as valid. In the DOM it shows a regex match attr on the input which matches the old token format, not the new one

**Comment by brumm** [comment]
That's really weird! I'll try make some time tonight to look into this further. Sorry for the inconvencience!

**Comment by grrowl** [comment]
![image](https://user-images.githubusercontent.com/907140/126854361-23fb8bc9-ef11-4521-95c7-148c946e638d.png)


fyi

**Comment by brumm** [comment]
Ah, thanks for the screenshot! You are indeed seeing the ReEnterInvalidToken view, from which I had forgotten to remove the token validation.

I removed all token validation attempts and just let you enter whatever.

0.2.6 also contains some more quality of life fixes:

- remove all token validation attempts
- force preview to scroll back to top
- try to fix overscroll behavior
- fix image preview background on dark mode
- fix stuck ui after history navigation

**Comment by brumm** [comment]
0.2.6 has been submitted to the respective extension stores, let me know if you have any more problems after the new version goes live :)

**Comment by grrowl** [comment]
just an FYI i had a problem entering the new token on the "your token is not valid or expired" view, Save was enabled but didn't work. i had to remove the whole extension and re-install it (clearing the extension storage) before i got the regular first-time setup input which did work.
