### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by zanedb** [brumm/tako#56]
given Apple's recent push towards web extensions in safari, i think this extension could be ported with relative ease. what do you think?

see [Apple's conversion guide](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari).

**Comment by brumm** [comment]
I am not planning on supporting Safari at this time. However I'd gladly accept a PR to do the conversion if you're interested :)

**Comment by zanedb** [comment]
i'd be happy to open a PR, however iirc an Apple Developer license is required to distribute it & i don't have one. do you?

**Comment by brumm** [comment]
I don't, unfortunately. It's also $100 a year I think.

**Comment by zanedb** [comment]
aw! well thanks anyway, appreciate your kind responses. have a good one!
