### ISSUE TITLE
Doesn't work with github submodules

### ISSUE THREAD

**Issue by FdelMazo** [brumm/tako#68]
On a repo using submodules Tako shows an error when clicking on the submodule itself:

![image](https://user-images.githubusercontent.com/25667102/173970243-344c8237-0fbf-4e5c-a834-2be82fe1c3b2.png)

Also, when ctrl-clicking (to open in a new tab), it browses to `https://github.com/<user>/<repo>/blob/main/<submodule-name>`, when it should actually browse to the submodules repo

This can be tested by adding a submodule to a repo with `git submodule add <github-url>` and then browsing that repo's page and clicking on the submodule

(I'm on firefox)

**Comment by brumm** [comment]
Hey, thanks for the report! Yeah, I never got around to making this work :) I really gotta spend some time on Tako and make it nice again

**Comment by FdelMazo** [comment]
Oh, it's really nice already!
