### ISSUE TITLE
Selected code looks blurry

### ISSUE THREAD

**Issue by yotam-frid** [brumm/tako#9]
Selected code has some sort of backdrop, which causes it to appear twice when selected and makes it harder to read.

![image](https://user-images.githubusercontent.com/37878305/78245253-d6ebba00-74ef-11ea-905e-d960f501c76d.png)

**Comment by DevNico** [comment]
This is a simple fix which I theoretically already have a solution for if @brumm helps me with #10 I can open a PR.

**Comment by brumm** [comment]
Yeah, seems like the syntax highlight theme is adding some text shadow? I'll happily accept your PR @DevNico once we get your setup working :)

**Comment by brumm** [comment]
Fixed, thanks @DevNico
